### ISSUE TITLE
Newest data is days old

### ISSUE THREAD

**Issue by TomGoBravo** [valorumdata/cmdc.py#13]
I have the latest installed from PyPI (nice!), 0.1.1:

```
>>> c = cmdc.Client()
>>> c.covid()
CMDC Client. Current request:
  -covid: {}
>>> df = c.fetch()
>>> df.vintage.max()
Timestamp('2020-06-06 00:00:00')
>>> df.dt.max()
Timestamp('2020-06-05 00:00:00')
>>> datetime.now().isoformat()
'2020-06-09T17:22:29.726187'
```

I'm expecting `df` to contain data from today or at least yesterday.

**Comment by sglyon** [comment]
Thanks!

Should be resolved now. If you are able to verify that it is resolved and remember to close the issue that'd be great!

**Comment by TomGoBravo** [comment]
Fixed, thank you.
