### ISSUE TITLE
Programmatic key handling

### ISSUE THREAD

**Issue by TomGoBravo** [valorumdata/cmdc.py#4]
I'd like to store the API key in github secret and pass it to the `Client` as a parameter. Currently it looks like the code only reads it from a file at a hard coded path... though I see a possible hacky work-around: subclass `Client` with my own object that has a `key` attribute.

**Comment by sglyon** [comment]
Thanks @TomGoBravo 

we have just merged #5 which allows you to pass the api key as a first argument when constructing `Client`

**Comment by cc7768** [comment]
This is "fixed again" in https://github.com/valorumdata/cmdc.py/commit/ba6f0c56f84049f3ec4b016d08b9975b74531965
