### ISSUE TITLE
frequent 500s getting https://api.covid.valorum.ai/swagger.json

### ISSUE THREAD

**Issue by TomGoBravo** [valorumdata/cmdc.py#7]
I'm seeing intermittent 500 errors fetching https://api.covid.valorum.ai/swagger.json

Besides fixing the server-side problem can you add something from the response in the ValueError? 

https://github.com/valorumdata/cmdc.py/blob/ba3ec9dd99d06811fdc659695a87de245b9d1f92/cmdc/client.py#L281 does it but https://github.com/valorumdata/cmdc.py/blob/ba3ec9dd99d06811fdc659695a87de245b9d1f92/cmdc/client.py#L132 doesn't.

Current stack trace doesn't show anything about the error:
```
Traceback (most recent call last):
...
  File "/home/tombrown/.pyenv/versions/covid-data-public/lib/python3.7/site-packages/cmdc/client.py", line 132, in __init__
    raise ValueError("Could not request the API structure -- try again!")
ValueError: Could not request the API structure -- try again!
```

**Comment by sglyon** [comment]
Yes, sorry about this. 

We will work on backend issue. And yes, we can put some notes in about the failed request!

**Comment by sglyon** [comment]
@TomGoBravo  have you seen this issue recently?
